name: JavaCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 9, 11 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }} 
          distribution: 'zulu'
      - name: Build with Maven
        run: ./mvnw clean package test

  build_jdk_ge_12:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 19]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
      - name: save java8 home
        run: |
          export JAVA8_HOME=$JAVA_HOME && echo $JAVA8_HOME
          echo "export JAVA8_HOME=$JAVA_HOME" > ~/.testenv
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - name: Build with Maven
        run: |
          source ~/.testenv
          java -version
          ./mvnw -version
          ./mvnw -Dmaven.compiler.fork=true -Dmaven.compiler.executable=$JAVA8_HOME/bin/javac clean package test